# Generated by Django 2.1.15 on 2021-12-30 04:02

import OBGG.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VMaininfoCom',
            fields=[
                ('c_match_name', models.CharField(db_column='C_Match_name', max_length=50, primary_key=True, serialize=False)),
                ('c_teama', models.CharField(blank=True, db_column='C_TeamA', max_length=50, null=True)),
                ('c_teamb', models.CharField(blank=True, db_column='C_TeamB', max_length=50, null=True)),
                ('c_tformat', models.CharField(db_column='C_Tformat', max_length=10)),
                ('c_score', models.CharField(blank=True, db_column='C_Score', max_length=20, null=True)),
                ('c_time_field', models.DateTimeField(db_column='C_Time_')),
                ('c_remarks', models.CharField(blank=True, db_column='C_Remarks', max_length=500, null=True)),
                ('c_commentary', models.CharField(blank=True, db_column='C_Commentary', max_length=50, null=True)),
                ('c_hostplace', models.CharField(blank=True, db_column='C_Hostplace', max_length=50, null=True)),
            ],
            options={
                'db_table': 'V_MainInfo_Com',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VMaininfoPlayer',
            fields=[
                ('c_team', models.CharField(db_column='C_Team', max_length=50, primary_key=True, serialize=False)),
                ('c_division', models.CharField(blank=True, db_column='C_Division', max_length=50, null=True)),
                ('c_game_id', models.CharField(blank=True, db_column='C_Game_id', max_length=50, null=True)),
                ('c_pname', models.CharField(db_column='C_Pname', max_length=50)),
                ('c_hero_1', models.CharField(blank=True, db_column='C_Hero_1', max_length=50, null=True)),
                ('c_hero_2', models.CharField(blank=True, db_column='C_Hero_2', max_length=50, null=True)),
                ('c_hero_3', models.CharField(blank=True, db_column='C_Hero_3', max_length=50, null=True)),
                ('c_pidentity', models.CharField(blank=True, db_column='C_Pidentity', max_length=10, null=True)),
                ('c_position', models.CharField(blank=True, db_column='C_Position', max_length=10, null=True)),
                ('c_nation', models.CharField(blank=True, db_column='C_Nation', max_length=50, null=True)),
                ('c_previous', models.CharField(blank=True, db_column='C_Previous', max_length=50, null=True)),
            ],
            options={
                'db_table': 'V_MainInfo_Player',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VMaininfoTeam',
            fields=[
                ('c_team', models.CharField(db_column='C_Team', max_length=50, primary_key=True, serialize=False)),
                ('c_division', models.CharField(db_column='C_Division', max_length=50)),
                ('c_coach', models.CharField(db_column='C_Coach', max_length=50)),
                ('c_introduction', models.CharField(blank=True, db_column='C_Introduction', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'V_MainInfo_Team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VUserCanChange',
            fields=[
                ('c_username', models.CharField(db_column='C_UserName', max_length=50, primary_key=True, serialize=False)),
                ('c_user_password', models.CharField(db_column='C_User_password', max_length=50)),
                ('c_user_sign', models.CharField(blank=True, db_column='C_User_sign', max_length=50, null=True)),
                ('c_user_sex', models.CharField(blank=True, db_column='C_User_sex', max_length=2, null=True)),
                ('c_user_email', models.CharField(db_column='C_User_email', max_length=50)),
                ('c_special_concern', models.CharField(blank=True, db_column='C_Special_concern', max_length=50, null=True)),
            ],
            options={
                'db_table': 'V_User_can_Change',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComT',
            fields=[
                ('c_p_match_id', models.CharField(db_column='C_P_Match_id', max_length=50)),
                ('c_p_battle_id', models.AutoField(db_column='C_P_Battle_id', primary_key=True, serialize=False)),
                ('c_teama', models.CharField(blank=True, db_column='C_TeamA', max_length=50, null=True)),
                ('c_teamb', models.CharField(blank=True, db_column='C_TeamB', max_length=50, null=True)),
                ('c_tformat', models.CharField(db_column='C_Tformat', max_length=10)),
                ('c_score', models.CharField(blank=True, db_column='C_Score', max_length=20, null=True)),
                ('c_time_field', models.DateTimeField(db_column='C_Time_')),
                ('c_commentary', models.CharField(blank=True, db_column='C_Commentary', max_length=50, null=True)),
                ('c_hostplace', models.CharField(blank=True, db_column='C_Hostplace', max_length=50, null=True)),
                ('c_remarks', models.CharField(blank=True, db_column='C_Remarks', max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': '成绩',
                'db_table': 'Com_T',
            },
        ),
        migrations.CreateModel(
            name='MatchT',
            fields=[
                ('c_p_f_match_id', models.CharField(db_column='C_P_F_Match_id', max_length=50, primary_key=True, serialize=False)),
                ('c_match_name', models.CharField(db_column='C_Match_name', max_length=50)),
                ('c_division', models.CharField(db_column='C_Division', max_length=50)),
                ('c_numteam', models.IntegerField(db_column='C_Numteam')),
                ('c_remarks', models.CharField(blank=True, db_column='C_Remarks', max_length=500, null=True)),
                ('c_ifnow', models.CharField(blank=True, db_column='C_Ifnow', max_length=3, null=True)),
            ],
            options={
                'verbose_name_plural': '赛事',
                'db_table': 'Match_T',
            },
        ),
        migrations.CreateModel(
            name='PlayerT',
            fields=[
                ('c_p_player_id', models.CharField(db_column='C_P_Player_id', max_length=50, primary_key=True, serialize=False)),
                ('c_p_team_id', models.CharField(db_column='C_P_Team_id', max_length=50)),
                ('c_pname', models.CharField(db_column='C_Pname', max_length=50)),
                ('c_pidentity', models.CharField(blank=True, db_column='C_Pidentity', max_length=10, null=True)),
                ('c_position', models.CharField(blank=True, db_column='C_Position', max_length=10, null=True)),
                ('c_hero_1', models.CharField(blank=True, db_column='C_Hero_1', max_length=50, null=True)),
                ('c_hero_2', models.CharField(blank=True, db_column='C_Hero_2', max_length=50, null=True)),
                ('c_hero_3', models.CharField(blank=True, db_column='C_Hero_3', max_length=50, null=True)),
                ('c_previous', models.CharField(blank=True, db_column='C_Previous', max_length=50, null=True)),
                ('c_nation', models.CharField(blank=True, db_column='C_Nation', max_length=50, null=True)),
                ('c_age', models.IntegerField(blank=True, db_column='C_Age', null=True)),
                ('c_game_id', models.CharField(blank=True, db_column='C_Game_id', max_length=50, null=True)),
                ('c_division', models.CharField(blank=True, db_column='C_Division', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': '选手',
                'db_table': 'Player_T',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('c_team', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name=OBGG.models.TeamT)),
                ('c_victory', models.CharField(max_length=50, verbose_name=OBGG.models.TeamScoreT)),
                ('c_score', models.CharField(max_length=50, verbose_name=OBGG.models.TeamScoreT)),
                ('c_defeated', models.CharField(max_length=50, verbose_name=OBGG.models.TeamScoreT)),
                ('c_victorys', models.CharField(max_length=50, verbose_name=OBGG.models.TeamScoreT)),
                ('c_defeated_s', models.CharField(max_length=50, verbose_name=OBGG.models.TeamScoreT)),
            ],
        ),
        migrations.CreateModel(
            name='TeamScoreT',
            fields=[
                ('c_p_team_id', models.CharField(db_column='C_P_Team_id', max_length=50, primary_key=True, serialize=False)),
                ('c_p_match_id', models.CharField(db_column='C_P_Match_id', max_length=50)),
                ('c_score', models.IntegerField(blank=True, db_column='C_Score', null=True)),
                ('c_victory', models.IntegerField(blank=True, db_column='C_Victory', null=True)),
                ('c_defeated', models.IntegerField(blank=True, db_column='C_Defeated', null=True)),
                ('c_victory_s', models.IntegerField(blank=True, db_column='C_Victory_s', null=True)),
                ('c_defeated_s', models.IntegerField(blank=True, db_column='C_Defeated_s', null=True)),
            ],
            options={
                'verbose_name_plural': '队伍积分',
                'db_table': 'Team_Score_T',
            },
        ),
        migrations.CreateModel(
            name='TeamT',
            fields=[
                ('c_p_f_team_id', models.CharField(db_column='C_P_F_Team_id', max_length=50, primary_key=True, serialize=False)),
                ('c_team', models.CharField(db_column='C_Team', max_length=50)),
                ('c_coach', models.CharField(db_column='C_Coach', max_length=50)),
                ('c_division', models.CharField(db_column='C_Division', max_length=50)),
                ('c_introduction', models.CharField(blank=True, db_column='C_Introduction', max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': '队伍',
                'db_table': 'Team_T',
            },
        ),
        migrations.CreateModel(
            name='UserT',
            fields=[
                ('c_p_userid', models.AutoField(db_column='C_P_UserID', primary_key=True, serialize=False)),
                ('c_username', models.CharField(db_column='C_UserName', max_length=50)),
                ('c_user_password', models.CharField(db_column='C_User_password', max_length=50)),
                ('c_user_email', models.CharField(db_column='C_User_email', max_length=50)),
                ('c_user_sign', models.CharField(blank=True, db_column='C_User_sign', max_length=50, null=True)),
                ('c_user_sex', models.CharField(blank=True, db_column='C_User_sex', max_length=2, null=True)),
                ('c_joindate', models.DateTimeField(db_column='C_Joindate')),
                ('c_special_concern', models.CharField(blank=True, db_column='C_Special_concern', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': '普通用户',
                'db_table': 'User_T',
            },
        ),
        migrations.AlterUniqueTogether(
            name='teamscoret',
            unique_together={('c_p_team_id', 'c_p_match_id')},
        ),
        migrations.AlterUniqueTogether(
            name='playert',
            unique_together={('c_p_player_id', 'c_p_team_id')},
        ),
        migrations.AlterUniqueTogether(
            name='comt',
            unique_together={('c_p_match_id', 'c_p_battle_id')},
        ),
    ]
